<div>
    <?php foreach($this->data as $pluginname => $entries): ?>
    <h5><?php echo $pluginname ?></h5>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Key</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($entries as $entry): ?>
            <tr>
                <td style="width: 200px;"><?php echo $entry["lw_key"] ?></td>
                <td><input style="height: 25px; width: 100%; font-size: 12px" type="text" name="lw_i18n[<?php echo $this->lang ?>][<?php echo $pluginname ?>][<?php echo $entry["lw_key"] ?>]" value="<?php echo $entry["text"] ?>"></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php endforeach;?>
</div>